const CONFIG = {
    prices: {
        onepager: 300,
        small: 600,
        medium: 900,
        large: 2500,
        ecommerce: 800,
        blog: 300,
        analytics: 150,
        hourlyRate: 60
    },
    translations: {
        fi: {
            "nav-services": "Palvelut",
            "nav-portfolio": "Portfolio",
            "nav-calculator": "Hintalaskuri",
            "nav-contact": "Ota yhteyttä",
            "hero-title": "Ota etumatka paremmilla kotisivuilla.",
            "hero-subtitle": "Modernit, nopeat ja näyttävät verkkosivut yrityksesi tarpeisiin.",
            "hero-cta": "Laske hinta",
            "hero-portfolio-cta": "Katso työmme",
            "services-title": "Palvelumme",
            "service-web-title": "Web-suunnittelu",
            "service-web-desc": "Modernit ja responsiiviset sivustot, jotka on optimoitu myyntiin ja näkyvyyteen.",
            "service-dev-title": "Kehitys",
            "service-dev-desc": "Puhdasta koodia, nopeita latausaikoja ja saumatonta toimivuutta kaikilla laitteilla.",
            "service-seo-title": "SEO & Ylläpito",
            "service-seo-desc": "Hakukoneoptimointi ja jatkuva tuki sivustosi menestyksen varmistamiseksi.",
            "portfolio-title": "Viimeisimmät työt",
            "calc-title": "Arvioi projektisi hintoja",
            "calc-type": "Sivuston laajuus",
            "type-onepager": "Onepager",
            "type-small": "1-3 sivua",
            "type-medium": "4-6 sivua",
            "type-large": "7-10 sivua",
            "calc-features": "Lisäominaisuudet",
            "feat-shop": "Verkkokauppa",
            "feat-blog": "Blogi",
            "feat-analytics": "Google Analytics",
            "calc-content": "Sisällön tuotanto (arvioitu h)",
            "calc-total-title": "Kustannusarvio",
            "summary-base": "Sivusto",
            "summary-features": "Ominaisuudet",
            "summary-total": "Kokonaishinta",
            "contact-title": "Pyydä tarjous",
            "placeholder-name": "Nimi",
            "placeholder-email": "Sähköposti",
            "placeholder-phone": "Puhelin",
            "placeholder-message": "Lisätietoja projektista...",
            "btn-submit": "Pyydä maksuton arvio"
        },
        en: {
            "nav-services": "Services",
            "nav-portfolio": "Portfolio",
            "nav-calculator": "Price Calculator",
            "nav-contact": "Contact",
            "hero-title": "Get Ahead with Better Websites.",
            "hero-subtitle": "Modern, fast, and stunning websites tailored to your business.",
            "hero-cta": "Get Quote",
            "hero-portfolio-cta": "View Work",
            "services-title": "Our Services",
            "service-web-title": "Web Design",
            "service-web-desc": "Modern, responsive websites optimized for sales and visibility.",
            "service-dev-title": "Development",
            "service-dev-desc": "Clean code, fast loading times, and seamless performance on all devices.",
            "service-seo-title": "SEO & Maintenance",
            "service-seo-desc": "Search engine optimization and ongoing support to ensure your success.",
            "portfolio-title": "Latest Work",
            "calc-title": "Estimate Your Project",
            "calc-type": "Project Size",
            "type-onepager": "One-pager",
            "type-small": "1-3 pages",
            "type-medium": "4-6 pages",
            "type-large": "7-10 pages",
            "calc-features": "Features",
            "feat-shop": "E-commerce",
            "feat-blog": "Blog",
            "feat-analytics": "Google Analytics",
            "calc-content": "Content Production (est. hours)",
            "calc-total-title": "Project Summary",
            "summary-base": "Base Website",
            "summary-features": "Add-ons",
            "summary-total": "Estimated Total",
            "contact-title": "Contact Us",
            "placeholder-name": "Name",
            "placeholder-email": "Email",
            "placeholder-phone": "Phone",
            "placeholder-message": "Tell us about your project...",
            "btn-submit": "Request Free Quote"
        }
    },
    portfolio: [
        {
            fi: { title: "Projekti Alfa", desc: "Moderni yrityssivusto" },
            en: { title: "Project Alpha", desc: "Modern corporate site" },
            image: "assets/project1.png",
            link: "#"
        },
        {
            fi: { title: "EcoKauppa", desc: "Uniikki verkkokauppa" },
            en: { title: "EcoStore", desc: "Boutique e-commerce" },
            image: "assets/project2.png",
            link: "#"
        },
        {
            fi: { title: "TechBlogi", desc: "Dynaaminen julkaisualusta" },
            en: { title: "TechBlog", desc: "Dynamic publishing platform" },
            image: "assets/project3.png",
            link: "#"
        }
    ]
};
